### PR TITLE
python tornado implementation of Maze server

### PR DESCRIPTION
**Pull request by mgk**
Thought I'd start the ball rolling on alternate language implementations of your example clients and servers.
Took a stab at a directory structure to hold other implementations that may come along.

### CODE REVIEW

**Comment by mamund** [comment]
@mgk:

This is _great_ and I like that you're thinking ahead on the folder structure. here's what i think would make this even better. 

instead of using `implementations/python/...` i think it'd be good to use `/implementations/mgk/...` or something similar. that way, in cases where two folks want to use the same base language, but provide a unique implementation, it would still be easy to include a new implementation set.

what do you think?

**Comment by mgk** [comment]
Thanks. Good point, it would be much better to make room for multiple implementations in each programming language. At the same time people often look for examples in a particular language, and you might get multiple contributions from a particular person.

So how about `name-language`  where name is usually a GH user name but could be a unique project name if one presents itself?

**Comment by mamund** [comment]
Let's use this format:

/{language}/{user}/

that way, people can scan by language and/or user and, if a single user
wants to do multiple langs it will be easy to organize. and, if a single
person does multiple implementations in the same lang, they''ll all be
under a single subdir.

cool?

​

**Comment by mgk** [comment]
Sounds good. Committed.

**Comment by mamund** [comment]
sweet.

mamund
+1.859.757.1449
skype: mca.amundsen
http://amundsen.com/blog/
http://twitter.com/mamund
https://github.com/mamund
http://linkedin.com/in/mamund

**Pull request closed without merging**
